### ISSUE TITLE
button issue

### ISSUE THREAD

**Issue by ModdersCentral** [mwilliams03/Pi-Touchscreen-basic#1]
The blue button is mangled, it is displayed at both sides of the screen but cropped off.

Display: http://www.adafruit.com/product/1601

**Comment by mwilliams03** [comment]
You can try changing the bottom position on the screen.

change these values;

```
//Our buttons.  X, Y, Width, Height
int buttonCords2[4] = {45,75,60,80};
int buttonCords3[4] = {135,75,60,80};
int buttonCords4[4] = {225,75,60,80};
```
